[package]
name = "scrt-prediction"
version = "1.0.0"
authors = ["Ryuhei Matsuda"]
edition = "2018"
description = "Price prediction package"
license = "Apache-2.0"
repository = "https://github.com/ryuheimat/scrt-prediction"
homepage = "https://scrt.network/"
documentation = "https://scrt.network/"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = []
# for quicker tests, cargo test --lib
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cosmwasm-storage = { git = "https://github.com/enigmampc/SecretNetwork", rev = "004c6bc" }
cosmwasm-std = { git = "https://github.com/enigmampc/SecretNetwork", rev = "004c6bc" }
schemars = "0.7"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
secret-toolkit = { git = "https://github.com/enigmampc/secret-toolkit", branch = "debug-print" }
